{% set version = "1.8.1" %}

package:
    name: avro
    version: {{ version }}

source:
    fn: avro-c-{{ version }}.tar.gz
    url: http://www-us.apache.org/dist/avro/avro-{{ version }}/c/avro-c-{{ version }}.tar.gz
    sha1: 93abae3d078e34900c1fee38fb0af2dcde624c8b

build:
    number: 0
    skip: True  # [win]

requirements:
    build:
        - cmake
        - snappy
        - zlib 1.2.*
    run:
        - snappy
        - zlib 1.2.*

test:
    commands:
        - test -f ${PREFIX}/lib/libavro.a  # [unix]

about:
  home: http://hadoop.apache.org/avro
  license: Apache 2.0
  summary: 'Avro is a serialization and RPC framework.'


extra:
  recipe-maintainers:
    - mariusvniekerk
